### ISSUE TITLE
Strange.  Every item in label_errors is False.

### ISSUE THREAD

**Issue by bigrat911** [cgnorthcutt/cleanlab#13]
thresholds is set either None or [0.9, ... 0.9]

**Comment by cgnorthcutt** [comment]
Please add information to reproduce this error otherwise I'll go ahead and close this.

**Comment by bigrat911** [comment]
`est_py, est_nm, est_inv, confident_joint, psx = estimate_py_noise_matrices_and_cv_pred_proba(
    X=self.train_x_vec,
    s=self.train_y_vec,
    clf=logreg(multi_class="ovr", solver="liblinear"),
    cv_n_folds=3,  # also tried 5
    thresholds=np.array([0.99, 0.99, 0.99]),  # also tried None and [0.9, 0.9, 0.9]
)
label_errors = get_noise_indices(
    s=self.train_y_vec,
    psx=psx,
    inverse_noise_matrix=est_inv,
    confident_joint=confident_joint,
)`
where shape of self.train_x_vec is (60000, 768) represented sentence embedding, and self.train_y_vec is (60000,) constituted in 3-class
label_errors is ALL False

**Comment by cgnorthcutt** [comment]
Can you please print the probabilities for ten random examples in psx. It should be a 10 by 3 matrix

**Comment by bigrat911** [comment]
> Can you please print the probabilities for ten random examples in psx. It should be a 10 by 3 matrix.

Thanks, I found the reason why psx is almost linearly separable.
Please close this issue.
