### ISSUE TITLE
Batch based noisy labels estimation

### ISSUE THREAD

**Issue by golunovas** [cgnorthcutt/cleanlab#18]
Thanks for sharing such a good tool!

I have a quite large dataset (10M samples) with 100K classes so the probabilities matrix of the whole dataset will take around 4Tb and it won't fit into RAM of my machine. Does it make any sense to split the dataset into batches and run the algorithm batch by batch?

**Comment by cgnorthcutt** [comment]
Good questions. Can you reduce the probability matrix to float16. or even unsigned int (8bits)?

**Comment by cgnorthcutt** [comment]
If you decide to split in batches, try to split up the classes into 100 batches, each of 1k classes, where all the label noise between classes will be self-contained in each batch (i.e. types of dogs go in one batch if label noise is between types of dogs, and all the airplanes go in another batch, if your label noise is unlikely to have dogs mislabeled as planes)

If the above is tricky for you, you can also just split it up randomly, but you may want to run it a few times and then combine all the label errors.

**Comment by golunovas** [comment]
Thank you for the quick response.

> Good questions. Can you reduce the probability matrix to float16. or if its still too big, potentially even unsigned int (8bits)?

I can reduce precision to 8bits per element but still, it's gonna be almost 1Tb.


> If you decide to split in batches, try to split up the classes into 100 batches, each of 1k classes, where all the label noise between classes will be self-contained in each batch (i.e. types of dogs go in one batch if label noise is between types of dogs, and all the airplanes go in another batch, if your label noise is unlikely to have dogs mislabeled as planes)

I've been trying to apply it for facial recognition task so I don't think splitting classes into self-contained batches is possible in my case.

> If the above is tricky for you, you can also just split it up randomly, but you may want to run it a few times and then combine all the label errors.

Is it better split them by classes or samples?

**Comment by cgnorthcutt** [comment]
In that case, try splitting into 100 groups of 1000 classes. You can group
them so that the batches are similar size. Re-run the entire process 5-10
times with different batch selections and take the concatenation of all the
label errors found.

(sent via mobile)
- Curtis

**Comment by golunovas** [comment]
Got it, thank you.
