### ISSUE TITLE
_compute_confident_joint_multi_label() fails for multilabel case with varying label counts per data point

### ISSUE THREAD

**Issue by UlliZimm** [cgnorthcutt/cleanlab#19]
**Problem:**

`_compute_confident_joint_multi_label()` produces a wrong count of unique labels `K` in line `192` when the labels consist of lists with varying label counts per data point. The problem lies in the function `np.unique()` which only works if the lists of labels all have the same length.

Example:
```
s = [[1, 2], [3]]
np.unique(s)

>>> array([list([1, 2]), list([3])], dtype=object)
```
You can see, that `np.unique()` counts unique lists instead of the entries in the lists. The desired output would be:

```>>> array([1, 2, 3])```

The problem lies in the fact, that numpy fails at flattening the list of lists if the lists have varying length.

**Proposed Solution:**

Explicitely flatten `s` before passing it to `np.unique()`: 
```
s = [[1, 2], [2, 3]]
s_flat = [i for l in s for i in l]
np.unique(s_flat)

>>> array([1, 2, 3])
```

**Comment by cgnorthcutt** [comment]
Thanks  this looks good. Would you like to get credit? If so, please send a pull request with the one line code change.

**Comment by cgnorthcutt** [comment]
@UlliZimm Thank you for the contribution. Added in this commit: https://github.com/cgnorthcutt/cleanlab/commit/40d619005588dfdfdeb9417b420d7a1d460918b8 Cheers.

**Comment by UlliZimm** [comment]
Thanks!
