### ISSUE TITLE
Regarding a tensorflow CNN example

### ISSUE THREAD

**Issue by BNAadministrator3** [cgnorthcutt/cleanlab#2]
Hi sir, 
I have implemented a tensorflow-version CNN example using your rank pruning algorithm. Could you please check the e-mail I sent (to cgn@mit.edu; e-mail subject: Regarding the confident learning library) and reply my questions? I would be very grateful.
Hopefully my codes are a positive commit to this repository.

**Comment by cgnorthcutt** [comment]
where's your pull request? preferably with testing :)

**Comment by BNAadministrator3** [comment]
Hi sir I just sent a email to cgn@mit.edu once more. title: Regarding the confident learning package（now cleanlab）. In my side, I was told the e-mail is sent successfully. Please inspect your spam boxes if you do not receive it again.
