### ISSUE TITLE
fns  is not defined

### ISSUE THREAD

**Issue by zhangabner** [cgnorthcutt/cleanlab#20]
fns  is not defined

**Comment by cgnorthcutt** [comment]
Can you provide details? Which function? At minimum can you give working code example that generates your error?

**Comment by zhangabner** [comment]
Hi,  it is in /imagenet_train_label_errors.ipynb
plt.figure(figsize=(50,40))
imglist = [transforms.ToTensor()(make3d(rs(Image.open(fn)))) for fn in fns[:32]]
show(make_grid(imglist, padding=1, normalize=True), savefig=True)

**Comment by cgnorthcutt** [comment]
@zhangabner Thanks! It was an ordering issue. I went ahead and re-factored the code and added some comments. See this commit: https://github.com/cgnorthcutt/cleanlab/commit/c340e9d7c1f193d0538780301107a2aa7093d331 and the updated file here: https://github.com/cgnorthcutt/cleanlab/blob/master/examples/imagenet/imagenet_train_label_errors.ipynb

This resolves your issue, so I'm closing. Happy holidays :)
