### ISSUE TITLE
What format of s and psx should be inputted into get_noise_indices() in a multi-label scenario

### ISSUE THREAD

**Issue by KongMingxi** [cgnorthcutt/cleanlab#23]
I have 20 samples with multi-label and 5 classes, such as:
[[2, 3, 4], [1, 3, 4, 5], [1, 3, 4], [1, 2, 3, 4, 5], [2, 3, 5], [1, 2, 4], [1, 3, 4, 5], [1, 3], [1, 5], [1, 3, 4, 5], [2, 3, 4], [3, 4], [4], [1, 3, 4], [2, 3, 4, 5], [1, 4], [3, 4], [3, 5], [2, 3, 5], [2, 5]]
I inputted this label list and a probabilities matrix as psx (shape=(20,5)) into get_noise_indices().
However, the error is:
  File "C:\Users\Anaconda2\envs\tf18\lib\site-packages\cleanlab\pruning.py", line 342, in get_noise_indices
    multi_label=multi_label,
  File "C:\Users\Anaconda2\envs\tf18\lib\site-packages\cleanlab\latent_estimation.py", line 303, in compute_confident_joint
    calibrate=calibrate,
  File "C:\Users\Anaconda2\envs\tf18\lib\site-packages\cleanlab\latent_estimation.py", line 216, in _compute_confident_joint_multi_label
    multi_label=True,
  File "C:\Users\Anaconda2\envs\tf18\lib\site-packages\cleanlab\latent_estimation.py", line 121, in calibrate_confident_joint
    confident_joint.T / confident_joint.sum(axis=1) * s_counts
ValueError: operands could not be broadcast together with shapes (5,5) (6,) 

Is there any wrong with my inputs?
What format of s and psx are correct in this multi-label scenario?

**Comment by cgnorthcutt** [comment]
Hi @KongMingxi. Easy fix. The labels need to start at 0. So, use labels 0, 1, 2, 3, 4 instead of 1, 2, 3, 4, 5.

**Comment by KongMingxi** [comment]
> Hi @KongMingxi. Easy fix. The labels need to start at 0. So, use labels 0, 1, 2, 3, 4 instead of 1, 2, 3, 4, 5.

Hi @cgnorthcutt 
Many thanks for your reply. Besides this format, can the one-hot labels be inputted directly?
Such as numpy array:
array([[0, 0, 1, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [0, 1, 0, 0, 1]])

**Comment by cgnorthcutt** [comment]
Hi @KongMingxi 

You can use `cleanlab.util.onehot2int` to convert your onehots to the appropriate format before using `cleanlab`. View the implementation here: https://github.com/cgnorthcutt/cleanlab/blob/master/cleanlab/util.py#L250

For example,

```python
from cleanlab.util import onehot2int
correctly_formatted_labels = onehot2int(onehot_matrix)
```

**Comment by nuaayuyang** [comment]
![image](https://user-images.githubusercontent.com/67412250/87033619-1de8fa00-c219-11ea-8e95-abd1867f0e87.png)
when i am using it to mutil lable  i have got this problem , how can i solve it

**Comment by cgnorthcutt** [comment]
Please share the function call and the first few lines of all inputs.

**Comment by nuaayuyang** [comment]
hi@cgnorthcutt  
![image](https://user-images.githubusercontent.com/67412250/87107624-d30bc880-c292-11ea-93b4-b563a3ac3310.png)
then I got this output

![image](https://user-images.githubusercontent.com/67412250/87107691-02223a00-c293-11ea-94b4-6c2119932b97.png)
the  number(above the image) which I print is s, my psx is a nxm matrix
