### ISSUE TITLE
Available for Semantic Segmentation?

### ISSUE THREAD

**Issue by super233** [cgnorthcutt/cleanlab#26]
Hi, obviously it's a great python package, and I'm doing research about **Pathological Image Segmentation with Noisy Labels**. Can it's available for my recent research?

**Comment by cgnorthcutt** [comment]
See: https://github.com/cgnorthcutt/cleanlab/issues/27

**Comment by sandeepnmenon** [comment]
I see "segmentation tasks" mention in "Future Features Planned" section
https://github.com/cgnorthcutt/cleanlab/blob/5a114647153815e017b31ae65e4cc7ea27702981/cleanlab/version.py#L53
