### ISSUE TITLE
Support for other modalities

### ISSUE THREAD

**Issue by mohitsharma29** [cgnorthcutt/cleanlab#27]
Hey

Thank you for this package. What changes will be required to make this work for Speech, Text, and Video?

**Comment by cgnorthcutt** [comment]
cleanlab supports all classification. Classification is modality-agnostic. Use any form of data you like.

All you need are the predicted probabilities for every example, and the labels. See: https://github.com/cgnorthcutt/cleanlab/tree/master/examples/cifar10

However you compute the predicted probabilities is up to you. For video, you may want to chunk it and use a model that takes 10s of video as input and yields a label for that ten seconds, and let each ten second clip be your example. 

To make this extra easy with simple text datasets, cleanlab has a fasttext port: https://github.com/cgnorthcutt/cleanlab/blob/master/cleanlab/models/fasttext.py

But the best way is to use whatever text classifier you like (e.g. GPT-2) to compute the predicted probabilities using cross-validation. Then it becomes a few lines of code to find label errors and remove them. Again, see: https://github.com/cgnorthcutt/cleanlab/tree/master/examples/cifar10
