### ISSUE TITLE
What is the correct format of s?

### ISSUE THREAD

**Issue by haoshuang0223** [cgnorthcutt/cleanlab#28]
I have 14312 training examples and the number of classes is 14. We all know that the format of psx is n*m where n is the number of examples and m is the number of classes. Thus, the shape of my psx numpy array is (14312, 14). 
I don't know what is the format of s. I guess it should be (14312,) and my s numpy array is like:
['6' '2' '10' ... '5' '0' '4']
But when I tried to run the following code:
ordered_label_errors = get_noise_indices(
	s=noisy_labels,
	psx=predicted_probabilities,
	prune_method='prune_by_class')
I got the follow error:
Traceback (most recent call last):
  File "run.py", line 18, in <module>
    prune_method='prune_by_class')
  File "/nethome/shao42/.local/lib/python3.5/site-packages/cleanlab/pruning.py", line 342, in get_noise_indices
    multi_label=multi_label,
  File "/nethome/shao42/.local/lib/python3.5/site-packages/cleanlab/latent_estimation.py", line 357, in compute_confident_joint
    confident_joint = calibrate_confident_joint(confident_joint, s)
  File "/nethome/shao42/.local/lib/python3.5/site-packages/cleanlab/latent_estimation.py", line 121, in calibrate_confident_joint
    confident_joint.T / confident_joint.sum(axis=1) * s_counts
ValueError: operands could not be broadcast together with shapes (0,0) (14,)

So I don't know where is wrong. Is it due to the format of s?

**Comment by cgnorthcutt** [comment]
For now, the `s` noisy labels array must be an array of 0-based integers. So all you need to do is run

python
```
noisy_labels = np.asarray([int(item) for item in s])
```

Or similarly, you could use

python
```
noise_labels = s.astype(int)
```

One of those should work for you.

**Comment by haoshuang0223** [comment]
Thanks, and that works for me.  After running the get_noise_indices() method, 'TRUE' means that it is a noisy label, right?

**Comment by cgnorthcutt** [comment]
@haoshuang0223 A boolean `True` in the output of `get_noise_indices()` indicates the example is a label error. It can help to verify this by viewing the data for all the examples where `get_noise_indices()` is True. The documentation (see the comments and docstrings for these methods) can be helpful here.
