### ISSUE TITLE
Assigned pulearning doesn't change the results much

### ISSUE THREAD

**Issue by sharifza** [cgnorthcutt/cleanlab#3]
From what I understand if I assign pulearning = 1 (in a binary classification problem), it should imply that the class of ones has no noise. Still after training, i get the following output from the confident_joint, est_py, est_nm and est_inv respectively as:

[[ 3216.  1179.]
 [16989. 14594.]]

[0.79313136 0.20686864]

[[0.15916852 0.07474799]
 [0.84083148 0.92525201]]

[[0.73174061 0.53791597]
 [0.26825939 0.46208403]]

Is there any other way to make sure no data points from class 1 are considered as noisy?

Thanks.

**Comment by mmdknr** [comment]
Bump!

**Comment by mmdknr** [comment]
Same issue :(

**Comment by cgnorthcutt** [comment]
Hi, thanks for the suggestion. Would either of you like to submit a pull request? It should look something of the form, `if K ==2 and pulearning... then`

**Comment by cgnorthcutt** [comment]
@mmdknr @sharifza -- fixed! See: https://github.com/cgnorthcutt/cleanlab/commit/12dd1ac7bb83710b80949c9ddf02bd828e72596c#diff-1cfd7e0a508d041378eb0e2de1f5ab3a 

Closing.
