### ISSUE TITLE
image segmentation with tensorflow?

### ISSUE THREAD

**Issue by ziyangwang007** [cgnorthcutt/cleanlab#30]
Hi,

Thanks for this excellent work and cleanlab.

When I try this library in my image semantic segmentation task with tensorflow. There is a bug:

    model = LearningWithNoisyLabels(clf=get_unet())
  File "/usr/local/lib/python3.6/dist-packages/cleanlab/classification.py", line 178, in __init__
    'The classifier (clf) must define a .predict_proba() method.')
ValueError: The classifier (clf) must define a .predict_proba() method.

Is there any advice?

thanks.

**Comment by cgnorthcutt** [comment]
There is no bug. Please read the error. Your classifier does not define .predict_proba(). You can see examples (just ctrl + f and search for predict_proba) in the readme and docs -- it explains how to set-up a classifier to work with cleanlab. If you don't want to do this, look at the CIFAR-10 example here https://github.com/cgnorthcutt/cleanlab/tree/master/examples/cifar10 for an example of computing the predicted probabilities in advance and using cleanlab without a classifier with predict_proba() defined.

**Comment by cgnorthcutt** [comment]
closing unless there are further questions. Cheers!
