### ISSUE TITLE
fasttext.py line 247,typeerror

### ISSUE THREAD

**Issue by datalee** [cgnorthcutt/cleanlab#36]
Anaconda3\lib\site-packages\cleanlab\models\fasttext.py", line 247, in <listcomp>
psx = [[p for _, p in sorted(list(zip(*l)), key=lambda x: x[0])] for l in list(zip(*pred))]
TypeError: zip argument #2 must support iteration

**Comment by datalee** [comment]
pred is a tuple,like (['label1', 'label2', 'label1', ,,,,], [0.78 0.21 0.39 ,,,,,])
list(zip(*pred)) is a list like [('label1', 0.78), ('label2', 0.21), ('label1', 0.39),,,,,]

**Comment by cgnorthcutt** [comment]
Hi @datalee , The fastext Python package became deprecated a year ago, and so CleanLab no longer officially supports it as a local dependency. You can still get it working, but it will require some finagling based on the many changes to the package over the past year and the syntax changes with each version. If you find one of my demos doesn't work, however, please post here and hopefully myself, or another avid CleanLab user, can get it working so you can build off of it.

**Comment by datalee** [comment]
> and then use them with cleanlab. Exampl

ok。tanks
