### ISSUE TITLE
one mistake in algorithm in the paper

### ISSUE THREAD

**Issue by tobyma2020** [cgnorthcutt/cleanlab#37]
It is an excellent work.  
In **Algorithm 1** of Section **C. The confident joint and joint algorithms** of the paper.
The code in part 2:
`_for i 1; m do_`
may mistake
`_for i 1; n do_`

**Comment by cgnorthcutt** [comment]
Yes @tobyma2020 , you are correct. Great catch. This was changed, but we are waiting until the next review cycle before releasing the updated version of the paper. The new version of the paper has a number of new and informative experiments and results, as well as improvements to the original results. Coming soon... (at the speed of publication which is slow).
