### ISSUE TITLE
number of mislabeled samples

### ISSUE THREAD

**Issue by wjx2** [cgnorthcutt/cleanlab#43]
Hello, 
thank you for your contributions! I have some problem,
how can I get more possible mislabeled samples with high probability？ 
Can I just enlarge the frac_noise to a larger number? The number of indices seems not linear with frac_noise.

**Comment by cgnorthcutt** [comment]
Hi @wjx2 
The max value you can use is `frac_noise = 1`. If your model is reasonably accurate (e.g. 80% accuracy), this will get all the likely mislabeled examples that have a high probability of being mislabeled. There are no more examples to obtain. We prove that for somewhat noisy predicted probabilities, cleanlab theoretically exactly finds label errors. In practice, the assumptions are not exactly held, but as long as the model is pretty accurate, cleanlab will find most of the errors. You can read more about this in Theorem 2 of the confident learning paper: https://arxiv.org/abs/1911.00068

If your model isn't very good, you can use cleanlab to find an initial set of errors, throw them out, and retrain on clean data. You can repeat this a few times to iteratively improve your dataset.
