### ISSUE TITLE
Question About the paper found in arxiv

### ISSUE THREAD

**Issue by CreatorZZY** [cgnorthcutt/cleanlab#49]
Dear \:
I'm sorry but i am confuse When i read the paper \<Confident Learning: Estimating Uncertainly in Dataset labels\> THAT in section 3.1, Why Confuseion matrix C define to given yk and predictions argmax(expr). Is that just like a Normalized Pivot table?

**Comment by cgnorthcutt** [comment]
I'm having a bit of trouble understanding your question. Please email the authors directly, with additional clarification. I will close this comment as it does not relate to the cleanlab package.
