### ISSUE TITLE
What is the algorithm behind this repo?

### ISSUE THREAD

**Issue by aluminumbox** [cgnorthcutt/cleanlab#5]
Hi, I am very interested in this package. I have a small clean dataset, and a large noisy dataset. I think this package can help my model better learn on the whole dataset.
What is the algorithm behind all these? Could you post a link or a paper? Many thanks!

**Comment by cgnorthcutt** [comment]
see https://github.com/cgnorthcutt/cleanlab#citations-and-related-publications

There are tens of algorithms that make-up this repo. They go far beyond our UAI paper (see link above). Given its value to the machine learning and data science communities, I've chosen to make this code open source and public prior to publishing. I"ll add the upcoming papers, once we have published. Thanks!

**Comment by cgnorthcutt** [comment]
UPDATE: the main algorithms behind cleanlab come from an emerging field in machine learning called confident. You can read about it [in this paper](https://arxiv.org/abs/1911.00068) and [this blog post](https://l7.curtisnorthcutt.com/confident-learning).
