### ISSUE TITLE
Sparse matrix support

### ISSUE THREAD

**Issue by gilad-rubin** [cgnorthcutt/cleanlab#6]
Hi!
I was wondering why the "utils.assert_inputs_are_valid" does not accept sparse matrices (such as scipy's csc/csr matrix) as input.
I understand that some models do not work well with sparse matrices and that could create errors while training, but I think it's reasonable to leave that for the user to handle .
What are your thoughts?

**Comment by cgnorthcutt** [comment]
Hi, thanks for your suggestion. I think its a reasonable suggestion, just be careful that it doesn't break other things. Please submit a pull request and I'll take a look. Thanks!

**Comment by cgnorthcutt** [comment]
Bumping @gilad-rubin for a PR. I personally do not have time to add this in from scratch, but I can take a look over your code with you via a Pull Request. I'll leave the issue open a few more months in case someone else is interested in championing this feature.

**Comment by cgnorthcutt** [comment]
@gilad-rubin  bump :)

**Comment by gilad-rubin** [comment]
Hey there 😊
I fixed it and added a pull request a few days ago. 
https://github.com/cgnorthcutt/cleanlab/pull/10

**Comment by cgnorthcutt** [comment]
Great! I have commented here:https://github.com/cgnorthcutt/cleanlab/pull/10#pullrequestreview-276695752 If you are able to add those further changes, they would be quick and helpful. Thanks!

**Comment by cgnorthcutt** [comment]
I will close this as communication can continue in https://github.com/cgnorthcutt/cleanlab/pull/10
