### ISSUE TITLE
Failed to load Pre-computed psx for every noise / sparsity condition in ciar10 dataset

### ISSUE THREAD

**Issue by kehuantiantang** [cgnorthcutt/cleanlab#65]
I tried to use `np.load('*.npy')` for loading the psx, but it give me the error
```
Cannot load file containing pickled data when allow_pickle=False
```
after I change to `psx = np.load(psx_path, allow_pickle=True)`, error again.
```
OSError: Failed to interpret file '/*/cifar10__train__model_resnet50__pyx.npy' as a pickle
```
numpy == 1.19.2
Any comment ? Thank you so much !^_^

**Comment by cgnorthcutt** [comment]
Hi @kehuantiantang , can you give more details. Which psx? Is there any more code you can share? What is your OS, python version.

**Comment by kehuantiantang** [comment]
Hi @cgnorthcutt, thank you so much for your reply.
I make mistake by download [npy](https://github.com/cgnorthcutt/confidentlearning-reproduce/blob/master/cifar10/cifar10_noisy_labels__frac_zero_noise_rates__0_0__noise_amount__0_0/cifar10__train__model_resnet50__pyx.npy) file by wget, I directly download by web-brower it works fine.
But I remain puzzled by two problems.
1. label_error_record array and shape is (50000, 1000), I keep the the first 10 classes, by `label_error_record[:, :10]`. It is the right way to get softmax probability ?  
2. [mask](https://github.com/cgnorthcutt/confidentlearning-reproduce/blob/master/cifar10/confidentlearning_and_coteaching/results/0_2/train_pruned_argmax/train_mask.npy) file just give me True/False label for samples, how can I get noise data according to sparsity and noise rate by mask?
Thanks a lot, wish you have a good day!

**Comment by cgnorthcutt** [comment]
Hi @kehuantiantang , 

RE 1: this should be fixed now. Can you pull the latest version of https://github.com/cgnorthcutt/confidentlearning-reproduce and try again. There should be just 10 classes now.

RE 2: You should be using these files instead for the masks: https://github.com/cgnorthcutt/confidentlearning-reproduce/tree/master/cifar10/cifar10_noisy_labels
The sparsity == frac_zero_noise_rates

**Comment by cgnorthcutt** [comment]
I've added a readme to clarify loading of noisy labels -- https://github.com/cgnorthcutt/confidentlearning-reproduce/blob/master/cifar10/cifar10_noisy_labels/README.md

**Comment by kehuantiantang** [comment]
Thank you for your help ^_^.
