### ISSUE TITLE
Multi Class Classification Errors

### ISSUE THREAD

**Issue by alexriedel1** [cgnorthcutt/cleanlab#67]
Hello!
I'm running into different errors trying to use `LearningWithNoisyLabels.fit()` in a multi-class classification. 
Having defined `X` with `X.shape` being `(46408,)` and `s` with `s.shape` being `(46408,)`.

`s` is the the format (which I guess is the right format as you suggest to use int labels instead of one hot labels)
`array([list([8, 5, 0]), list([14, 0]), list([6, 1]), list([16, 10]),
       list([14, 0]), list([0]), list([14]), list([13, 0]), list([12, 0]),
       list([14]), list([3]), list([7, 2]), list([9]), list([5]),
       list([12]), list([6]), list([3]), list([13]), list([9, 16, 0, 13]),
       list([14, 2]),  ...)`

First I'm running into:
`TypeError: cleanlab requires zero-indexed labels (0,1,2,..,m-1), but in your case: np.unique(s) = [list([0]) list([0, 13]) list([0, 13, 17]) list([0, 17]) list([1])
 list([1, 0]) list([1, 0, 13]) list([1, 2]) list([1, 2, 0])
 list([1, 2, 7]) list([1, 2, 13]) list([1, 3]) list([1, 3, 0]) ...`

inside `assert_inputs_are_valid()`. Which makes total sense, as my labels contain more than one element. If I skip that check, I'll be running into 
`ValueError: You appear to be using a legacy multi-label data representation. Sequence of sequences are no longer supported; use a binary array or sparse matrix instead - the MultiLabelBinarizer transformer can convert to this format.`
because sklearn wants one hot labels for generating the cv folds...

Question:
Am I missing anything? Is this even made for multi-class problems? How can I get over the errors?

**Comment by cgnorthcutt** [comment]
Hi, cleanlab works fine for multi-class, but for now, you need to use a work-around (running the cleaning and re-training steps seprately, instead of just using `LearningWithNoisyLabels()`)

Your issue was addressed here: https://github.com/cgnorthcutt/cleanlab/issues/55

I'll add support for multi-label classification directly into `LearningWithNoisyLabels` in the future.
