### ISSUE TITLE
Using keras model for label noise prediction

### ISSUE THREAD

**Issue by panwarnaveen9** [cgnorthcutt/cleanlab#7]
I have build the custom class as mentioned in readme

```python
class CustomKerasModel(Sequential):

    def __init__(self,name=None, max_features=20000, batch_size=128, epochs=10, validation_split=0.1):
        super(CustomKerasModel, self).__init__(name=name)
        self.add(Embedding(max_features, 128))
        self.add(Bidirectional(LSTM(32, return_sequences = True)))
        self.add(GlobalMaxPool1D())
        self.add(Dense(20, activation="relu"))
        self.add(Dropout(0.05))
        self.add(Dense(num_classes, activation="softmax"))
        self.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
        self.batch_size = batch_size
        self.epochs = epochs
        self.validation_split = validation_split

    def fit(self, X, y):
        y_one_hot = to_categorical(y)
        return self.model.fit(X, y_one_hot, batch_size=self.batch_size, epochs=self.epochs, validation_split=self.validation_split)
    
    def score(self, X, y):
        return self.model.evaluate(X, y, batch_size=128)[1]
```

and then to predict the label  I am using 
```python
from cleanlab.latent_estimation import estimate_py_noise_matrices_and_cv_pred_proba
est_py, est_nm, est_inv, confident_joint, psx = estimate_py_noise_matrices_and_cv_pred_proba(
    X=X,
    s=y,
    clf = CustomKerasModel(max_features=max_features,batch_size=batch_size, epochs=epochs, validation_split=0.1)
)
```

But its not working I am getting following error 

```
~/anaconda3/lib/python3.6/copy.py in _deepcopy_dict(x, memo, deepcopy)
    238     memo[id(x)] = y
    239     for key, value in x.items():
--> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
    241     return y
    242 d[dict] = _deepcopy_dict

~/anaconda3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
    167                     reductor = getattr(x, "__reduce_ex__", None)
    168                     if reductor:
--> 169                         rv = reductor(4)
    170                     else:
    171                         reductor = getattr(x, "__reduce__", None)

TypeError: can't pickle _thread.RLock objects
```

Could anyone please provide the solution to this problem or right way to use 
keras model for lable noise prediction ??

**Comment by cgnorthcutt** [comment]
Hi @panwarnaveen9, thanks for bringing this up. Are you still having this issue? It looks like some Keras models have similar issues (and this isn't related to cleanlab at all). Can you take a look at this Stackoverflow post and let me know if you are still having the issue: https://stackoverflow.com/questions/44855603/typeerror-cant-pickle-thread-lock-objects-in-seq2seq

**Comment by cgnorthcutt** [comment]
bump @panwarnaveen9

**Comment by panwarnaveen9** [comment]
@cgnorthcutt I will try solution suggested on stackover link. Also can you confirm the way I am using using keras model for pre-trained model is right ? do you have any examples somewhere in documentation ?

**Comment by cgnorthcutt** [comment]
@panwarnaveen9 You should define `predict(X)` and `predict_proba(X)` methods as well in your class, that take in a test dataset and output an np.array of predictions for `predict(X)` and a 2-D matrix np.array of probabilities for `predict_proba(X)`. 

An even easier way is just run your model however you want, get the predicted probabilities and save them. Then, copying directly from the documentation:

```python
from cleanlab.pruning import get_noise_indices
# We computed psx, est_inv, confident_joint in the previous example.
label_errors = get_noise_indices(
    s=train_labels_with_errors, 
    psx=predicted_probabilities_as_a_matrix_from_your_model, 
)
```
You should computed `predicted_probabilities_as_a_matrix_from_your_model` using cross-validation or however you like, but make sure they are computed out-of-sample (holdout probabilities).

**Comment by cgnorthcutt** [comment]
Closing shortly if no further issues.

**Comment by qysnn** [comment]
Hello @cgnorthcutt, by out-of-sample do you mean I should train multiple models on different portions of data like the cross-validation? For example, if I have 10000 samples with noisy labels, should I cut them into 4 parts of 2500 samples and then train first model on part 1,2,3 and predict 4, second model on part 1,2,4 and predict 3... and then put all predicted 10000 labels as the `predicted_probabilities_as_a_matrix_from_your_model` to feed to the cleanlab?

**Comment by cgnorthcutt** [comment]
@qysnn Yes, unless you have another dataset from the same data distribution to train on, just use cross-validation. For sklearn models, cleanlab does this for you automatically. See: https://github.com/cgnorthcutt/cleanlab/blob/master/cleanlab/latent_estimation.py#L700

If you want to use PyTorch or Tensorflow or whatever-you-want, then you have two options:
1. wrap your model in a sklearn looking class. Example: https://github.com/cgnorthcutt/cleanlab/blob/master/cleanlab/models/mnist_pytorch.py#L78
2. (what I usually do) Train using cross-validation. I wrote code to do this for most PyTorch models (currently the code is for CIFAR-10, but can be easily modified for any dataset). Here: https://github.com/cgnorthcutt/cleanlab/blob/master/examples/cifar10/cifar10_train_crossval.py#L347 and then you run this code for each fold like this:

```bash
$ python3 cifar10_train_crossval.py \
    -a resnet50 --gpu 0 --cvn 4 --cv 0  \
    --train-labels LABELS_PATH.json CIFAR10_PATH
$ python3 cifar10_train_crossval.py \
    -a resnet50 --gpu 1 --cvn 4 --cv 1  \
  --train-labels LABELS_PATH.json CIFAR10_PATH
$ python3 cifar10_train_crossval.py \
    -a resnet50 --gpu 2 --cvn 4 --cv 2  \
  --train-labels LABELS_PATH.json CIFAR10_PATH
$ python3 cifar10_train_crossval.py \
    -a resnet50 --gpu 3 --cvn 4 --cv 3  \
  --train-labels LABELS_PATH.json CIFAR10_PATH
```

More examples are here: https://github.com/cgnorthcutt/cleanlab/tree/master/examples/cifar10
