### ISSUE TITLE
Balance the training set for cross-validation? 

### ISSUE THREAD

**Issue by weiwen0221** [cgnorthcutt/cleanlab#72]
Hi, I want to ask should I balance the training set if I'm doing cross-validation?

**Comment by cgnorthcutt** [comment]
Yes. Use `StratifiedFold`. You can copy how cleanlab does it if you're looking for an example: https://github.com/cgnorthcutt/cleanlab/blob/ec735a06d93d2ce90ccb60d9b8a44b495169e159/cleanlab/latent_estimation.py#L610

**Comment by weiwen0221** [comment]
Thank you so much for your reply!
