### ISSUE TITLE
Sanity Check: is cleanlab only for classification problems?

### ISSUE THREAD

**Issue by JRMeyer** [cgnorthcutt/cleanlab#76]
Hi @cgnorthcutt,

Firstly, this is some great work you've kindly open-sourced, thanks!

I've looked through the blog post and skimmed docs, and I think I know the answer, but I'd like a quick sanity check.

In multiple places it is mentioned that `cleanlab` (i.e. confident learning) is for "supervised learning" or "weakly supervised learning", but it also seems to me that it **will only work for classification problems**. Is this the case?

`cleanlab` isn't appropriate for other supervised learning problems like sequence-to-sequence or regression, correct? I care most about Speech-to-Text and Text-to-Speech, and I would love a tool like this to weed out bad transcriptions. The noise matrix assumes a finite set of classes, however, which means `cleanlab` won't work in these cases. Do I understand correctly? Are there any hacks I might be able to use?

Thanks,
Josh

**Comment by cgnorthcutt** [comment]
`cleanlab` `clean`s `lab`els. So, as long as you have labels, `cleanlab` can be used. `cleanlab` is not used for unsupervised learning. I've used and seen it used for regression effectively by bucketing targets into groups, creating classes/labels. I've also used it for segmentation (reframed as a classification task). So, the short of it is yes cleanlab is for classification, but depending on your setting, you may be able to re-frame your problem as a classification task.

**Comment by cgnorthcutt** [comment]
For your use case of text-to-speech and speech-to-text, I've used cleanlab (and the field of confident learning in general) extensively for these use cases. My applications may have been different, but the way I formulate the problem usually is:

class 0 - does the sentence contain word 0
class 1 - does the sentence contain word 1

etc.

**Comment by JRMeyer** [comment]
oh that's an interesting way to re-frame the problem... and there should be no problem if there's 500k+ classes? I guess the algo should still hold, but maybe it will take a *very* long time?

Do you have anything written up about using `cleanlab` for speech transcripts? The (main?) blog post is really well written, and I'd love to read about the details of speech data and transcripts

Do you have anything you can share about your work with speech data? did you use librispeech?

thanks for the quick reply!

**Comment by cgnorthcutt** [comment]
My work on speech data + transcripts was with Google Research (2019) and Amazon AI Research (2017), neither approved publicly releasing the work so my hands are tied (I don't blame them -- confident learning reveals how often some of their services fail which is something companies generally do not make public).

When you have a minimum demo working, would you mind sharing a pull request -- it would be great to include this in `cleanlab/examples`!

Re 500k classes -- I don't recommend doing this. Confident learning builds a `num_classes` x `num_classes` matrix to estimate uncertainty across classes. Try to keep the classes low. It works for ImageNet (1000 classes) just fine, but I haven't tested it with more than 2000 classes and you'll probably need some serious RAM.

**Comment by JRMeyer** [comment]
understood, and I'll think keep in mind that you'd welcome the PR. 

As for the num_classes x num_classes matrix... I'd have to think about doing this efficiently. I get that sub-setting the dataset isn't ideal. In anycase I'll close this issue, and again - I appreciate the responses:)
