### ISSUE TITLE
typo in the comments

### ISSUE THREAD

**Issue by amirhfarzaneh** [cgnorthcutt/cleanlab#8]
Shouldn't [this line](https://github.com/cgnorthcutt/cleanlab/blob/de8fd42c53c006e59c689b9f9e62783bbeb85c34/cleanlab/latent_algebra.py#L81) be:

`# 'ps' is p(s=k) = noise_matrix * p(**y**=k)`

**Comment by cgnorthcutt** [comment]
Thanks! Fixed.
